### PR TITLE
add zh_tw and fix language name

### PR DESCRIPTION
**Pull request by SSARCandy**

### CODE REVIEW

**Comment by ccseer** [comment]
Hi~~
thanks for your translation.

I was wondering if maybe I can add a Hong Kong flag to the Settings page to avoid political issue. I'm not interesting in political at all, but I don't want to get involved in trouble.

**Comment by ccseer** [comment]
Thanks for your translation~~

**Comment by ccseer** [comment]
http://1218.io/translators.html

**Comment by SSARCandy** [comment]
👍

**Pull request merged**
