### PR TITLE
Create Ukrainian.ts

### PR DESCRIPTION
**Pull request by shoorik007**
Added the Ukrainian language.

### CODE REVIEW

**Comment by ccseer** [comment]
Thank you!!

**Comment by shoorik007** [comment]
👍

**Comment by ccseer** [comment]
I will add  it in next release.  
http://1218.io/seer/translators.html

Do you have a license for Seer Pro? I can send you a complimentary one.

**Comment by ccseer** [comment]
One more thing, looks like you are not using the latest ts file
image

**Comment by ccseer** [comment]
The instruction can be found here: 
image

**Comment by shoorik007** [comment]
Yes, I need a Seer Pro license.
Ok, I'll update the file.

**Pull request merged**
